name: GraalVM Build and Release

on:
  workflow_dispatch:
  push:
    tags:
      - v*

jobs:
  build:
    name: transcli on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
      - uses: actions/checkout@v6

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '25.1'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build transcli
        run: |
          ./gradlew nativeCompile
          ./build/native/nativeCompile/transcli -h

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: transcli-${{ matrix.os }}-${{ runner.arch }}-${{ github.ref_name }}
          path: |
            ./build/native/nativeCompile/transcli
          if-no-files-found: error

  release:
    name: Release transcli
    needs: build
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Download transcli
        uses: actions/download-artifact@v8

      - name: Release
        uses: softprops/action-gh-release@v3
        if: github.ref_type == 'tag'
        with:
          files: |
            transcli-*
